### ISSUE TITLE
Replace references/variable names from 'white' list to 'allow' list

### ISSUE THREAD

**Issue by mattgreg** [cla-assistant/github-action#16]
URL to the linked Repo/Org:
https://github.com/ockam-network/cla-action

We are using a fork of CLA-Assistant and would like to replace references of white/black lists to allow/deny lists

**Comment by ibakshay** [comment]
@mattgreg, yes absolutely and I really appreciate it. Please raise a Pull Request after you have changed naming from `white` list users to `allow` list users in your fork. I will be very happy to accept your contribution :).

**Comment by ibakshay** [comment]
Hi @mattgreg, I have changed all references from `whitelist` to `allowlist`.. It will be reflected in next release :).

**Comment by ibakshay** [comment]
I have rolled out a new release `v1.4.1-alpha` and these changes are already reflected :).
