### ISSUE TITLE
Release v1.4.1 has wrong version number

### ISSUE THREAD

**Issue by Shane32** [cla-assistant/github-action#25]
Release v1.4.1-alpha was released as version `@v1.4.1-alpha` instead of `v1.4.1-alpha`.  This causes this error when using the samples:

`An action could not be found at the URI 'https://api.github.com/repos/cla-assistant/github-action/tarball/v1.4.1-alpha'`

And the temporary solution is to use this line:

`uses: cla-assistant/github-action@@v1.4.1-alpha`

Except that it doesn't work because of this error:

`The workflow is not valid. .github/workflows/cla.yml (Line: 15, Col: 15): Expected format {org}/{repo}[/path]@ref. Actual 'cla-assistant/github-action@@v1.4.1-alpha',Input string was not in a correct format.`

So, v1.4.1 doesn't work at all.  I suggest re-releasing it with the correct version number.

**Comment by Shane32** [comment]
Note that v1.4.0 is identical to v1.4.1 and can be used with:

`uses: cla-assistant/github-action@V1.4.0-alpha`

**Comment by ibakshay** [comment]
You are absolutely right. It is my mistake. Anyways, even `v1.4.0-alpha` has a bug so please don't use this version. 

You can use the latest version `uses: cla-assistant/github-action@v1.4.2-alpha` in your projects :).  This release also fixed the issue which you have created  [here](https://github.com/cla-assistant/github-action/issues/26)

**Comment by Shane32** [comment]
Thanks!
