### ISSUE TITLE
path-To-cladocument property is missing from action.yml

### ISSUE THREAD

**Issue by Shane32** [cla-assistant/github-action#26]
The `path-To-cladocument` property is missing from the `action.yml` file, causing this warning when running the github action:

`Unexpected input(s) 'path-To-cladocument', valid inputs are ['path-to-signatures', 'branch', 'blockchain-storage-flag', 'label', 'empty-commit-flag', 'allowlist']`

I suggest adding something like this:
```yml
  path-To-cladocument:
    description: "Fully qualified web link to cla document"
```

**Comment by Shane32** [comment]
It would probably be preferred if it was lowercase, like `path-to-cladocument`, but then you probably also need to change `url.ts` to match

**Comment by ibakshay** [comment]
@Shane32, thank you for raising this issue. It is a bug from my side and I am working on it. I will probably fix and draft a new release by tomorrow. I will let you know once I am done 😄 . 
 >It would probably be preferred if it was lowercase, like path-to-cladocument, but then you probably also need to change url.ts to match

Sure, makes sense. I am thinking of this naming `path-to-cla-document`

**Comment by ibakshay** [comment]
I have rolled a new release `v1.4.2-alpha` and this release should fix this issue :). Thank you for raising this issue once again ..
