### ISSUE TITLE
Cannot read property 'push' of undefined

### ISSUE THREAD

**Issue by matextrem** [cla-assistant/github-action#28]
The action is failing when it's triggered on an PR.

The error says: `Cannot read property 'push' of undefined`

You can see the error here: https://github.com/gnosis/safe-react/runs/932889230?check_suite_focus=true

**Comment by ibakshay** [comment]
Hi @matextrem, looks strange to me. Could you please check If the `master` branch is protected ??..

**Comment by matextrem** [comment]
@ibakshay master branch is protected that's the reason why I'm pointing to another branch in the CLA action script.

**Comment by mikheevm** [comment]
@matextrem the branch didn't exist on the repository

**Comment by davidalbela** [comment]
I have the same question, why CLA send that error in other branches that are not protected?
