### ISSUE TITLE
How to configure `allowlist` for dependabot?

### ISSUE THREAD

**Issue by shunkakinoki** [cla-assistant/github-action#34]
## Required

Thanks for the awesome repo! 🔥🔥🔥
I was trying to configure how to bypass dependabot for cla action, but have trouble in doing so

The slugs I've tried but have not worked:

```yml
allowlist: imgbot,dependabot*
```

```yml
allowlist: dependabot*
```

```yml
allowlist: dependabot[bot]
```

URL to the linked Repo/Org:
https://github.com/sentrei/sentrei/pull/132
https://github.com/sentrei/sentrei/pull/132/checks?check_run_id=951771337

What is the expected result?

The check passes

What happens instead?

The check fails

**Comment by shunkakinoki** [comment]
```yml
          github.actor != 'github-actions[bot]' ||
          github.actor != 'dependabot[bot]' ||
          github.actor != 'dependabot-preview[bot]' ||
          github.actor != 'imgbot' ||
          github.actor != 'imgbot[bot]' ||
          github.event.comment.body == 'recheckcla' || 
          github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA' || 
          github.event_name == 'pull_request'
```

for now.

**Comment by ibakshay** [comment]
Hi @shunkakinoki, Thank you very much:)  I tried in one of my [test repo](https://github.com/ibakshay/todo-app/pull/8) and both the below slugs seems to be working fine. 
 ```yml 
allowlist: dependabot[bot]
allowlist: bot*
```
But when I was testing, I also found out that there is one bug - this cla action creating an empty commit sometimes - which I will fix and roll out a new release by this weekend.

**Comment by shunkakinoki** [comment]
hi @ibakshay 

Thanks for the reply. 
Yes, my bad it's working great! Thanks for the work. Seriously appreciate it!
I missed out on the fact that when you update a PR branch, that actor has to be included in the allowlist, or it will fail.
