### ISSUE TITLE
[BUG] Status check failing on sign

### ISSUE THREAD

**Issue by AnandChowdhary** [cla-assistant/github-action#39]
**Describe the bug**
When someone makes a PR who hasn't signed the CLA, the status check fails and there is a comment requesting them to sign. When they sign, the comment text is updated to "All contributors have signed the CLA" but the status check is still "failing". However, when a new label is added, CLA Assistant runs again and adds a new, passing, status check. So there are two checks now, one passing and one failing.

**Expected behavior**
The status check passes when the comment is updated the "All contributors have signed the CLA"

**Screenshots**
<img width="936" alt="Screen Shot 2020-08-08 at 11 32 17@2x" src="https://user-images.githubusercontent.com/2841780/89703713-d5814100-d96a-11ea-8bb8-9f60bdec2b26.png">

**Comment by ibakshay** [comment]
Hi @AnandChowdhary, The event `issue_comment` doesn't have access to the [commit status](https://docs.github.com/en/rest/reference/repos#statuses). This failed check is from the previous commit of the user. You can see under the `actions` tab that the workflow run when the user signed has actually passed like the below screenshot. 

![Screen Shot 2020-08-08 at 09 32 42](https://user-images.githubusercontent.com/33329946/89705061-394f3e00-d95a-11ea-84fc-f5b949af36fe.png)

Right now, one workaround for you is to manually re-run the previously failed CLA check for `pull_request` event when the user committed by clicking the `re-run jobs` button like below. 

![Screen Shot 2020-08-08 at 09 29 27](https://user-images.githubusercontent.com/33329946/89705078-79aebc00-d95a-11ea-9d07-9318da984141.png)

Nevertheless, I am working on automating this use-case by consuming [GitHub Actions workflow re-run API](https://developer.github.com/v3/actions/workflow-runs/#re-run-a-workflow) whenever a contributor signs the CLA i:e `issue_comment` event.

**Comment by ibakshay** [comment]
I will let you know here, soon after I am done with it. So, let's keep this issue open for tracking.

**Comment by simonmeggle** [comment]
Hi @ibakshay , I still have this problem with the latest release, see #81 ...
Just to go sure: is it sufficient to have the `PERSONAL_ACCESS_TOKEN` defined as a repository secret? Is this the token used to [rerun](https://docs.github.com/en/rest/actions/workflow-runs#re-run-a-workflow) the workflow?

**Comment by simonmeggle** [comment]
I just tried it with a new pull request: the bot is asking for signature, the user signs, but the action still fails. 
Example:
https://github.com/elabit/robotframework-checkmklibrary/pull/3

![image](https://user-images.githubusercontent.com/1897410/186707001-0fac8564-d2d9-49cc-95ee-07360089aeb1.png)

**Comment by jfoliveira** [comment]
I've faced the same issue this week contributing to `Devopness` open source repository: https://github.com/devopness/devopness

After many hours of work from another Devopness contributor he suggested me to review the token permissions and we figure out that the `workflow` permission is required for this action so it can update commit status.

I'm using GitHub Personal Access Token `classic`.

### What DOES NOT work ❌ 
Without granting the token the scope `workflow` the commit status is not updated, therefore the pull request checks block the PR from being merged.

Also the CLA assistant does not add to the debug log the line `Rerunning build run` defined in https://github.com/contributor-assistant/github-action/blob/dbc1c64d82d3aad5072007a41fff2828ae6d23ec/src/pullRerunRunner.ts#L22

<img width="1167" alt="image" src="https://github.com/contributor-assistant/github-action/assets/1943318/609c37db-3fa7-4a6d-88ec-072cec64fbc6">

### What WORKS!!!!!! ✅ 🎉 

Granting the token the `workflow` scope then `recheck` works as expected:

<img width="1143" alt="image" src="https://github.com/contributor-assistant/github-action/assets/1943318/b24fdfa8-be8f-4ac9-814f-97ef9c56a929">


### Notes:
1. It would be nice if the CLA Assistant failed explicitly everytime it is enabled to call a GitHub REST API endpoint, stating the returned error message, as that could save us many hours trying to debug this action's source code
2. Perhaps the bot could also check or log or document all required permissions upfront, so users are aware of that when configuring their access tokens


Apart from that, thanks @ibakshay for maintaining and providing this action.
Pretty useful! Great job! 💟
