### ISSUE TITLE
[BUG] CLA assistant failing by default

### ISSUE THREAD

**Issue by AnandChowdhary** [cla-assistant/github-action#45]
Since updating to the most recent alpha, all the CLA checks are failing.

![Screen Shot 2020-08-24 at 22 45 28](https://user-images.githubusercontent.com/2841780/91075323-853cfb00-e65b-11ea-9410-d3c9224aece5.png)

**Comment by ibakshay** [comment]
Hi @AnandChowdhary, I have removed the inputs `blackchain-storage-flag` and  `empty-commit-flag` as we are not using it anymore. That is why you are getting this error. Could you please take the updated CLA workflow file from the [readme file](https://github.com/cla-assistant/github-action/blob/master/README.md)?.

**Comment by AnandChowdhary** [comment]
Thanks!
