### ISSUE TITLE
[Feature] Add ability to skip signed comment after CLA is signed

### ISSUE THREAD

**Issue by harsimranmaan** [cla-assistant/github-action#68]
**Is your feature request related to a problem? Please describe.**
Everytime the bot comments on the PR, it generates notifications which may not be ideal for all situations. I usually read all my github emails and the bot comments spam them.

**Describe the solution you'd like**
It should be possible to optionally skip the comment and maybe replace it with an alternative like a like on the PR or something.

**Describe alternatives you've considered**
Setting the custom message to "" but not sure if that'd work

**Additional context**
For reference see https://github.com/bigpanther/shipanther/pull/256

**Comment by harsimranmaan** [comment]
Using empty string does not skip the comment

**Comment by ibakshay** [comment]
Hi @harsimranmaan, thank you for the feature request. Yes, you are right.  It totally makes sense not to add CLA bot comment on every PR if the contributor has already signed the CLA. Green [PR status check](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-status-checks) from CLA bot will be more than sufficient for this use-case.  I will implement this feature soon and get back to you. Let's keep this issue open till then :)

**Comment by AndrewGable** [comment]
Big fan of this feature as well 👍

**Comment by ibakshay** [comment]
This feature is available in today's new release 😄 
```yml
uses: cla-assistant/github-action@v2.1.0-alpha
```

**Comment by ibakshay** [comment]
So, the bot won't post any PR comment if the contributor has already signed the CLA when creating a PR. Only PR status check will be set to success.

**Comment by AndrewGable** [comment]
We've been using this over at https://github.com/Expensify/Expensify.cash and it's been working great, thank you!
