### ISSUE TITLE
[BUG] Error thrown when user reviewer comments after a merge

### ISSUE THREAD

**Issue by AndrewGable** [cla-assistant/github-action#72]
**Describe the bug**
1. PR author signs CLA (https://github.com/Expensify/expensify-common/pull/327#issuecomment-769344096)
2. Reviewer approves PR (https://github.com/Expensify/expensify-common/pull/327#pullrequestreview-581568256)
3. Reviewer merges PR (https://github.com/Expensify/expensify-common/pull/327#event-4280480581)
4. Reviewer comments on PR (https://github.com/Expensify/expensify-common/pull/327#issuecomment-771792976)
5. Error is thrown on that comment (https://github.com/Expensify/expensify-common/actions/runs/531402880)

> `Could not update the JSON file: Error occured when creating or editing the comments of the pull request: Error occured when getting all the comments of the pull request: Unable to create comment because issue is locked.`

**To Reproduce**
I believe you just have to comment on a PR after it's merged, however, the above should help reproduce.

**Expected behavior**
Ideally no error is thrown, it's not clear to the PR reviewer why an action should fail after the PR is merged and causes confusion. If you could check for the locked PR case, maybe a warning would cause less confusion.

**Screenshots**
<img width="1502" alt="Screen Shot 2021-02-02 at 10 48 49 AM" src="https://user-images.githubusercontent.com/2838819/106641319-4c774b00-6544-11eb-946d-9def704e811c.png">

**Comment by ibakshay** [comment]
Hi @andrei-panov, Ideally CLA step shouldn't even be triggered when there is a PR comment other than `I have read the CLA Document and I hereby sign the CLA` or `recheck`. 

Could you please check the regex action which you are using? . I feel there is a bug in their side. I might be wrong though. 
``` yml
- name: CLA Assistant
    if: ${{ steps.recheck.outputs.match != '' || steps.sign.outputs.match != '' }} || github.event_name == 'pull_request_target'
```
I have checked without regex validation and the CLA step is not triggered. 

``` yml
- name: CLA Assistant
   if: (github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA') || github.event_name == 'pull_request_target'
```

Test repository -> https://github.com/ibakshay/test-repo-2/pull/2 
Action logs -> https://github.com/ibakshay/test-repo-2/runs/1837047127?check_suite_focus=true
<img width="1763" alt="Screenshot 2021-02-05 at 08 31 03" src="https://user-images.githubusercontent.com/33329946/107003218-b5510400-678c-11eb-82b8-7ac741f5f381.png">

**Comment by AndrewGable** [comment]
We haven't seen this anymore, thank you for your reply!
