### ISSUE TITLE
[Feature] Make locking pull request an optional flag

### ISSUE THREAD

**Issue by AndrewGable** [cla-assistant/github-action#77]
**Is your feature request related to a problem? Please describe.**
In our open source repo we sometimes have contributors who accidentally close their PRs, which locks them as mentioned here: https://github.com/cla-assistant/github-action/issues/70#issuecomment-767647956

The contributors cannot comment after this happens, leaving them to ask if we can manually unlock the pull request so they can comment and continue working on their solution. Otherwise they have to create a new pull request which can be time consuming.

**Describe the solution you'd like**
I would prefer the "locking" behavior to be an optional flag and we'd prefer it to not lock on our repository. We understand that contributors could delete or edit their comments, but we are OK with this trade off.

**Describe alternatives you've considered**
Alternatively, could we "unlock"/"re-open" the PR once the PR is reopened?

**Additional context**
Here is an example pull request (https://github.com/Expensify/Expensify.cash/pull/1739) where it's locked, then reopened.

**Comment by ibakshay** [comment]
Hi @AndrewGable, Absolutely, 100 percent!.  This feature request makes a lot of sense. I will work on this topic and I will get it done before the end of next week :) . I will let you know here soon after I have made a new release :)

**Comment by ibakshay** [comment]
This feature is implemented and reflected in the new release `v2.1.2-beta` :) . 
You need to add this input `lock-pullrequest-aftermerge: false` to your [CLA action](https://github.com/Expensify/Expensify.cash/blob/5cc1a8178568e36665cd6e9503014730ced1be2e/.github/workflows/cla.yml#L39)  and then the pull request won't be locked automatically by CLA action bot anymore.

**Comment by AndrewGable** [comment]
Thank you @ibakshay! I updated all our repos to the latest version.
