### ISSUE TITLE
[BUG] Allow list in cla.yml not working as expected

### ISSUE THREAD

**Issue by swathimr** [cla-assistant/github-action#82]
**Describe the bug**
Specifying my user name in allow list still executes the github action.

**To Reproduce**
1. Add allow list to cla.yml `allowlist: gitusername,bot*`. 
2. commit changes and update a test read me file.
3. Notice the cla assistant github action in-spite the allow list  has the user name.
4. This also does not add the signature in to the signature.json file.
5. Keeping only bot in allowlist `allowlist: bot*` works as expected.

**Expected behavior**
If the user name is specified in the allow list the cla assistant github action should not execute.

**Screenshots**
![Screen Shot 2021-04-12 at 3 30 16 PM](https://user-images.githubusercontent.com/8705617/114450962-acbde500-9ba4-11eb-96cb-f33cfeb3cb35.jpg)

![Screen Shot 2021-04-12 at 3 35 42 PM](https://user-images.githubusercontent.com/8705617/114451043-c2cba580-9ba4-11eb-9c72-71862fdc1309.jpg)

**Comment by ibakshay** [comment]
Hi @swathimr,
I am sorry for the late response. Could you please send the link to your pull request ?. I will check it out and get back to you :)

**Comment by swathimr** [comment]
Here it is https://github.com/swathimr/edgeworkers-examples/pull/38. This should not trigger the action since I have added my github username in the allowlist. However I still see the action triggered and prompted for sign.

**Comment by swathimr** [comment]
Hi @ibakshay did you get a chance to take a look at this ?

**Comment by ibakshay** [comment]
I just checked and it looks like it is a bug from my side. Sorry for that. 
Actually I retriggered using `recheck` pull request comment and the CLA check has passed. https://github.com/swathimr/edgeworkers-examples/actions/runs/773348859. It is just that, this CLA action is not retriggering the old failed Pull Request CLA status check and updating the [CLA comment](https://github.com/swathimr/edgeworkers-examples/pull/38#issuecomment-822684885). You can also see that CLA status check is green for your other recent [Pull request](https://github.com/swathimr/edgeworkers-examples/pull/38#issuecomment-822684885) . 


### Workaround 
- push an empty commit in your branch `swathimr-patch-2` using this command `git commit --allow-empty -m "<COMMIT MESSAGE>"`

**Comment by ibakshay** [comment]
For your information,

This issue occurs only when you have added a user to the `allowlist` after creating a new Pull request.

**Comment by ibakshay** [comment]
Hi @swathimr, this is not exactly a bug. This is the default behaviour of GitHub Actions platform. So, [this CLA workflow](https://github.com/swathimr/edgeworkers-examples/pull/38/checks?check_run_id=2383730189) is failed because your name was not added to the `allowlist` when this workflow is triggered. You have added your name to the `allowlist` later after this workflow is failed. However, this failed workflow is still taking the old version of the [CLA workflow file](https://github.com/swathimr/edgeworkers-examples/blob/master/.github/workflows/cla.yml). 

So, in this case, you can simply push an empty commit to this branch `swathimr-patch-2` with this command
``` yaml
git commit --allow-empty -m “empty commit for retriggering CLA bot”
git push
```

**Comment by swathimr** [comment]
Thanks for the response Akshay ! closing this.
